/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#1b1a29",
        "primary-fixed": "#eaddff",
        "on-secondary-fixed-variant": "#8c0053",
        "on-primary-container": "#ede0ff",
        "outline-variant": "#ccc3d8",
        "on-secondary-fixed": "#3e0022",
        "primary-container": "#7c3aed",
        "surface-container-highest": "#dae2fd",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#e4e0f5",
        "on-error": "#ffffff",
        "surface-variant": "#dae2fd",
        "surface-container-low": "#f2f3ff",
        "tertiary-container": "#676577",
        "on-error-container": "#93000a",
        "tertiary": "#4f4d5e",
        "surface-container-high": "#e2e7ff",
        "inverse-primary": "#d2bbff",
        "inverse-surface": "#283044",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#e7e4f8",
        "on-surface-variant": "#4a4455",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d2d9f4",
        "primary": "#630ed4",
        "on-secondary-container": "#600037",
        "on-tertiary-fixed-variant": "#464555",
        "on-primary-fixed": "#25005a",
        "on-background": "#131b2e",
        "surface-bright": "#faf8ff",
        "surface-tint": "#732ee4",
        "secondary-fixed-dim": "#ffb0cd",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#d2bbff",
        "tertiary-fixed-dim": "#c7c4d8",
        "secondary": "#b4136d",
        "on-primary-fixed-variant": "#5a00c6",
        "on-surface": "#131b2e",
        "inverse-on-surface": "#eef0ff",
        "secondary-container": "#fd56a7",
        "secondary-fixed": "#ffd9e4",
        "background": "#faf8ff",
        "surface-container": "#eaedff",
        "on-secondary": "#ffffff",
        "outline": "#7b7487",
        "surface": "#faf8ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-sm": "0.5rem",
        "gutter-mobile": "0.75rem",
        "space-2xs": "0.125rem",
        "gutter-desktop": "1.5rem",
        "space-xl": "2rem",
        "margin-mobile": "1rem",
        "space-base": "1rem",
        "margin-desktop": "2rem",
        "space-xs": "0.25rem",
        "space-2xl": "3rem",
        "space-lg": "1.5rem",
        "space-3xl": "4rem",
        "space-md": "0.75rem"
      },
      fontFamily: {
        "label-md": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "title": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "label-md": ["0.875rem", { "lineHeight": "1.25rem", "letterSpacing": "0.005em", "fontWeight": "500" }],
        "code-sm": ["0.75rem", { "lineHeight": "1.25rem", "fontWeight": "400" }],
        "title": ["1.125rem", { "lineHeight": "1.5rem", "letterSpacing": "-0.005em", "fontWeight": "600" }],
        "body-md": ["0.875rem", { "lineHeight": "1.375rem", "fontWeight": "400" }],
        "headline-lg": ["2.25rem", { "lineHeight": "2.75rem", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-sm": ["0.75rem", { "lineHeight": "1.125rem", "fontWeight": "400" }],
        "body-lg": ["1rem", { "lineHeight": "1.625rem", "fontWeight": "400" }],
        "display": ["3rem", { "lineHeight": "3.5rem", "letterSpacing": "-0.025em", "fontWeight": "700" }],
        "headline-md": ["1.5rem", { "lineHeight": "2rem", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "label-sm": ["0.75rem", { "lineHeight": "1rem", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "headline-lg-mobile": ["1.75rem", { "lineHeight": "2.25rem", "letterSpacing": "-0.015em", "fontWeight": "700" }],
        "headline-sm": ["1.25rem", { "lineHeight": "1.75rem", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    }
  },
  plugins: [],
}
