"""phase3_schema_update

Revision ID: e027e415d92b
Revises: 5ed8694e3ab5
Create Date: 2026-08-29 02:17:12.536702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e027e415d92b'
down_revision: Union[str, Sequence[str], None] = '5ed8694e3ab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_barrier_category', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('primary_barrier_detail', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('comparison_behavior', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('desired_information', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('evidence', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ai_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('model_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('prompt_version', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('schema_version', sa.String(), nullable=True))
        batch_op.drop_column('confidence')
        batch_op.drop_column('primary_barrier')

    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('unique_conversation_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_diversity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ai_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sources_present', sa.JSON(), nullable=True))
        batch_op.drop_column('confidence_score')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence_score', sa.FLOAT(), nullable=True))
        batch_op.drop_column('sources_present')
        batch_op.drop_column('ai_confidence')
        batch_op.drop_column('source_diversity')
        batch_op.drop_column('source_count')
        batch_op.drop_column('unique_conversation_count')
        batch_op.drop_column('category')

    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_barrier', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.FLOAT(), nullable=True))
        batch_op.drop_column('schema_version')
        batch_op.drop_column('prompt_version')
        batch_op.drop_column('model_name')
        batch_op.drop_column('ai_confidence')
        batch_op.drop_column('evidence')
        batch_op.drop_column('desired_information')
        batch_op.drop_column('comparison_behavior')
        batch_op.drop_column('primary_barrier_detail')
        batch_op.drop_column('primary_barrier_category')

    # ### end Alembic commands ###
