"""Add collection_runs metrics

Revision ID: 5ed8694e3ab5
Revises: e4a654080fff
Create Date: 2026-08-29 00:24:57.681410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ed8694e3ab5'
down_revision: Union[str, Sequence[str], None] = 'e4a654080fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('records_fetched', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('records_new', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('records_duplicate', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_runs', schema=None) as batch_op:
        batch_op.drop_column('error_message')
        batch_op.drop_column('records_duplicate')
        batch_op.drop_column('records_new')
        batch_op.drop_column('records_fetched')

    # ### end Alembic commands ###
